
package com.mycompany.danimanjaronpractica1m7;

/**
 *
 * @author danim
 */

public class Calculadora extends javax.swing.JFrame {
    
private String TextDisplay = "";    //Emmagatzema el ttext que es mostra al JLabel del display, tan l'operacio completa com el numero que es va escribint
private int PrimerNumero = 0;   //Emmagatzema el primer numero abans de seleccionar un operador
private int SegonNumero = 0;    //Emmagatzema el segon numero abans de seleccionar un operador
private String Operador = "";   //Emmagatzema el operador.seleccionat
private boolean ComprovacioNum = false;     //Indica si s'ha introduit un numero i s'ha seleccionat un operador
private int Resultat = 0;  //Emmagatzema el resultat de l'operacio entre PrimerNumerp i SegonNumero
private boolean esNouOperador = false;  //  Indica si s'ha seleccionat un nou operador per netejar el display abans d'introduir el següent número
private boolean errorEstado = false;    //Indica si hi ha hagut un error (ex: divisió per 0
private String operacioCompleta = "";   // Emmagatzema l'operació completa per mostrar al display.
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button7 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonSum = new javax.swing.JButton();
        ButtonRest = new javax.swing.JButton();
        ButtonMulti = new javax.swing.JButton();
        ButtonEquals = new javax.swing.JButton();
        Diskplay = new javax.swing.JLabel();
        ButtonDiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        Button7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        ButtonD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtonD.setText("D");
        ButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        ButtonC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtonC.setText("C");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        ButtonSum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtonSum.setText("+");
        ButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumActionPerformed(evt);
            }
        });

        ButtonRest.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtonRest.setText("-");
        ButtonRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRestActionPerformed(evt);
            }
        });

        ButtonMulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtonMulti.setText("*");
        ButtonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiActionPerformed(evt);
            }
        });

        ButtonEquals.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtonEquals.setText("=");
        ButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualsActionPerformed(evt);
            }
        });

        Diskplay.setBackground(java.awt.Color.white);
        Diskplay.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Diskplay.setForeground(java.awt.Color.black);
        Diskplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Diskplay.setAutoscrolls(true);
        Diskplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Diskplay.setOpaque(true);

        ButtonDiv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonDiv.setText("/");
        ButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Diskplay, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonRest, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ButtonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Diskplay, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(ButtonRest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ButtonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        afegirNumero("4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
      afegirNumero("8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
      afegirNumero("6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void ButtonRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRestActionPerformed
   manejarOperador("-");
    }//GEN-LAST:event_ButtonRestActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        afegirNumero("7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
       afegirNumero("0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        afegirNumero("2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        afegirNumero("3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        afegirNumero("5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
       afegirNumero("9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void ButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumActionPerformed
        manejarOperador("+");
    }//GEN-LAST:event_ButtonSumActionPerformed
    
    
    private void ButtonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiActionPerformed
      manejarOperador("*");
    }//GEN-LAST:event_ButtonMultiActionPerformed

    
    private void ButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualsActionPerformed
    if (!TextDisplay.isEmpty() && ComprovacioNum) {     //Primer verifiquem que el Jlabel NO esigui biut i que s'hagi escollit un operador
          SegonNumero = Integer.parseInt(TextDisplay);  //Converteix el segon número introduït a un enter.
          CalcularResultat();   //Crida al mètode per calcular el resultat segons l'operador.
                
          if (!errorEstado){    // Si no hi ha hagut cap error, mostra el resultat.
                 operacioCompleta += TextDisplay + " = " + Resultat;  //Inclou l'operacio completa al registre
                Diskplay.setText(String.valueOf(Resultat)); // Mostra el resultat al display. ValueOf, s'utilitza per convertir el resultat en un String.
                ComprovacioNum = false; // Reseteja l'indicador del primer número.
                TextDisplay = String.valueOf(Resultat); /// Actualitza el display amb el resultat.
                esNouOperador = true;   // Prepara per a la següent operació.
    }//GEN-LAST:event_ButtonEqualsActionPerformed
   }
 }
  
    /**
 * Afegeix un número al display.
 * Si s'ha seleccionat un nou operador, es neteja el display abans d'afegir el número.
 * @param numero Número seleccionat per l'usuari.
 */

    private void afegirNumero(String numero) {
        if (esNouOperador) {    //Si es nouOperador, el Jlabel es neteja per borrar els numeros previs.
            TextDisplay = "";  // Neteja el display per al nou número.
             esNouOperador = false;     ///Indica que s'està introduint un nou número.
        }
        
        TextDisplay += numero;  // Afegeix el número al text del display.
        operacioCompleta += numero; // Actualitza l'operació completa.
        Diskplay.setText(operacioCompleta);  // Mostra l'operació completa al display.
    }
  
    /**
 * Maneja l'operador seleccionat.
 * Si ja hi ha un operador previ seleccionat, calcula el resultat de l'operació anterior.
 * @param nouOperador L'operador seleccionat (suma, resta, multiplicació, divisió).
 */
  
    private void manejarOperador(String nouOperador) {
        if (ComprovacioNum) {
            // Si ja s'ha seleccionat un operador anterior, realitzem l'operació anterior
            SegonNumero = Integer.parseInt(TextDisplay);    // Converteix el segon número a enter.
            CalcularResultat();     // Calcula el resultat de l'operació.
                if (!errorEstado) { // Si no hi ha hagut errors, actualitza el display.
                PrimerNumero = Resultat;    // El resultat es converteix en el nou primer número.
                operacioCompleta = Resultat + nouOperador;  // Actualitza l'operació completa.
                Diskplay.setText(operacioCompleta); // Mostra l'operació actualitzada al display.
            } 
        } else {
            /// Si no s'ha seleccionat cap operador anterior, emmagatzema el primer número.
            PrimerNumero = Integer.parseInt(TextDisplay);   // Converteix el primer número a enter.
            operacioCompleta = PrimerNumero  + nouOperador; // Crea la nova operació completa.
            Diskplay.setText(operacioCompleta); // Mostra l'operació al display.
        }
      
        TextDisplay = "";   // Neteja el display per al següent número.
        Operador = nouOperador;  // Definim el nou operador
        ComprovacioNum = true;  // Indiquem que el primer número ja ha estat introduït
        esNouOperador = true;   // Indica que s'ha seleccionat un nou operador.
   }
   
   /**
 * Calcula el resultat de l'operació segons l'operador seleccionat.
 * També maneja errors com la divisió per zero.
 */
   private void CalcularResultat() {   
       switch(Operador) {
        case "+":
            Resultat = PrimerNumero + SegonNumero;
            break;
        case "-":
            Resultat = PrimerNumero - SegonNumero;
            break;
        case "*":
            Resultat = PrimerNumero * SegonNumero;
            break;
        case "/":
            if (SegonNumero == 0) {
               Diskplay.setText("Error! no es pot dividir entre 0");  // Maneig de divisió per zero
               errorEstado = true;  // Activa l'estat d'error.
               return;
            } else {
                Resultat = PrimerNumero / SegonNumero;
            }
            break;
        default:
            Resultat = SegonNumero; // Si no hi ha operador, només mostra el segon número.
            break;
    }
}
 
   /**
 * Reinicia la calculadora quan es pressiona el botó "C".
 * Neteja el display i reinicia totes les variables.
 */
    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        TextDisplay = "";   // Neteja el text del display.
        Diskplay.setText(TextDisplay);  // Actualitza el display.
        ComprovacioNum = false;     // Reseteja la comprovació del primer número.
        Operador = "";  // Neteja l'operador seleccionat.
        esNouOperador = false;  // Reseteja l'indicador de nou operador.
        Resultat = 0;   // Reinicia el resultat.
        PrimerNumero  = 0;  // Reinicia el primer número.
        SegonNumero = 0;    // Reinicia el segon número.
        operacioCompleta = "";  /// Neteja l'operació completa.
        errorEstado  = false;   //Reinicia l'estat d'error, per poder fer operacions despres que surti
    }//GEN-LAST:event_ButtonCActionPerformed

    
    
    private void ButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDActionPerformed
        if (!TextDisplay.isEmpty()) { // Verifica que el TextDisplay no estigui buit
            TextDisplay = TextDisplay.substring(0, TextDisplay.length() - 1);   // Elimina l'últim carácter del TextDisplay
            Diskplay.setText(TextDisplay); 
        }
    }//GEN-LAST:event_ButtonDActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        afegirNumero("1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void ButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivActionPerformed
    manejarOperador("/");
    }//GEN-LAST:event_ButtonDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonD;
    private javax.swing.JButton ButtonDiv;
    private javax.swing.JButton ButtonEquals;
    private javax.swing.JButton ButtonMulti;
    private javax.swing.JButton ButtonRest;
    private javax.swing.JButton ButtonSum;
    private javax.swing.JLabel Diskplay;
    // End of variables declaration//GEN-END:variables
}
